name: websocket_rails
version: 0.2.0
author: Marcel Sackermann <marcel@m0gg.org>
description: package to communicate with a websocket managed by [websocket-rails/websocket-rails](https://github.com/websocket-rails/websocket-rails/tree/master/lib/assets/javascripts/websocket_rails) gem
homepage: https://github.com/m0gg/dart-websocket_rails
dependencies:
  logging: ">=0.9.3 <0.10.0"
